- vshard/replicaset.lua
Before this patch is_connected returned true
only if connection state was 'active'.
However if call modified schema, connecton state
changed to 'fetch_schema' that led to reconnect
This patch fixes this behaviour and saves is_connecton
status then schema fetching.
Closes #199
Related https://github.com/tarantool/tarantool/commit/d0e333191d3f81aa3ed035ce2ce53e74a18417c1
> Consider connection as valid if its state is 'fetch_schema'

- .gitignore
- vshard-scm-1.rockspec
* This patch solves problem with missing TARANTOOL_INCLUDE_DIR
cmake error, which occurs due to tarantool installation
directory differs from default.
> Add TARANTOOL external dependency to rockspec

- .travis.yml
Sometimes "deploy" stage fails it prevents the update of rockspec.
To avoid this let's move rockspec publishing into separate stage.
> travis-ci: move rockspec publishing into separate stage

- .travis.yml
This section doesn't do anything useful but leads to fail for some
stages. This patch just removes it.
> travis-ci: remove before_deploy section

- .github/workflows/fast_testing.yml
Issue #294 is fixed and it's time to enable tarantool 2.9 testing.
> ci: enable tarantool 2.9 testing

- .github/workflows/fast_testing.yml
- .github/workflows/reusable_testing.yml
- test/CMakeLists.txt
Problem: when tests start and one of them fails, the test run stops, and
other tests are not executed, we exit after the first test failure. It's
not convenient since as a developer I would like to see all test results
and understand the impact of my changes on all project functionalities.
> ci: disable fail-fast behaviour for tests

- vshard-scm-1.rockspec
GitHub is going to disable unencrypted Git protocol, so `git://` URLs
will stop working soon (see [1]).
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Part of https://github.com/tarantool/tarantool/issues/6587
> rockspec: use git+https:// for git repository URL

- test/luatest_helpers/vtest.lua
- test/router-luatest/router_test.lua
- vshard/router/init.lua
- vshard/storage/init.lua
Closes #312
@TarantoolBot document
Title: vshard.router.map_callrw() format of `return_raw` result
`vshard.router.map_callrw()` supports `return_raw` option (in the
version of Tarantool which have it at all).
When there was an error, the result is the same as always:
`nil, err, err_uuid`. No changes.
When the call was a success, the result is a map of the format
`{[replicaset_uuid] = msgpack.object}`. The `msgpack.object` here
stores a MessagePack array with the results returned from the
storage's map-function.
The usecase is the same as for when bare netbox is used - to avoid
decoding of the results into Lua land. Helpful when the router is
used as a proxy and the results received from the storage are big.
Example:
```Lua
local res = vshard.router.map_callrw('my_func', args, {..., …
```
> router: support return_raw in map_callrw()

- test/lua_libs/util.lua
- test/rebalancer/receiving_bucket.result
- test/rebalancer/receiving_bucket.test.lua
- test/router/map-reduce.result
- test/router/map-reduce.test.lua
- test/router/retry_reads.result
- test/router/retry_reads.test.lua
- test/router/router.result
- test/router/router.test.lua
- test/router/sync.result
- test/router/sync.test.lua
- test/storage/ref.result
- test/storage/ref.test.lua
Issue https://github.com/tarantool/tarantool/issues/6144 suggests changing the exception thrown on
time-out error, which requires changing the tests in this repository to
tests that will run on both types of exception thrown.
> test: new check for timeout errors from net.box

- test/router-luatest/router_test.lua
- vshard/router/init.lua
The patchset makes the router use `take_array()` method of msgpack iterator instead of manual tail cut via an intermediate Lua table.
> Use `msgpack_iterator:take_array()` method

- test/instances/storage.lua
- test/luatest_helpers/server.lua
- test/luatest_helpers/vtest.lua
- test/router-luatest/router_test.lua
- test/storage/recovery_errinj.result
- test/storage/recovery_errinj.test.lua
- test/unit-luatest/config_test.lua
- test/unit-luatest/util_test.lua
- test/unit/config.result
- test/unit/config.test.lua
- vshard/cfg.lua
- vshard/replicaset.lua
- vshard/router/init.lua
- vshard/storage/init.lua
- vshard/util.lua
The patchset allows to use multilisten and SSL features. Although there was a way to use multilisten before (as long as the URIs were strings and `listen` was passed to each storage in the root of its vhsard config), it is now easier.
> SSL and multilisten support

- .luacheckrc
- test/instances/storage.lua
- test/luatest_helpers/vtest.lua
- test/storage-luatest/storage_1_1_test.lua
- test/unit-luatest/util_test.lua
- vshard/storage/init.lua
- vshard/util.lua
The patchset fixes a problem when rebalancer couldn't work if there were spaces with varbinary field type, or with double field type which stored at least one number not having a fraction. https://github.com/tarantool/vshard/issues/327
> Transfer bucket tuples as is without re-coding via Lua

- .luacheckrc
- test/instances/router.lua
- test/instances/storage.lua
- test/luatest_helpers/vtest.lua
- test/rebalancer/bucket_ref.result
- test/rebalancer/rebalancer2.result
- test/rebalancer/rebalancer2.test.lua
- test/router-luatest/router_test.lua
- test/router/router.result
- test/router/router.test.lua
- test/storage-luatest/garbage_collector_test.lua
- test/storage-luatest/storage_1_1_test.lua
- test/storage-luatest/storage_2_test.lua
- test/storage/recovery.result
- test/storage/recovery.test.lua
- test/storage/recovery_errinj.result
- test/storage/recovery_errinj.test.lua
- test/storage/storage.result
- test/storage/storage.test.lua
- test/unit-luatest/error_test.lua
- vshard/error.lua
- vshard/storage/init.lua
- vshard/util.lua
The patchset starts work on the big issue of bucket refs being not protected from incorrect changes of _bucket. Mostly that is about the main bug which allows to garbage collect a bucket on a master instance even if it has some read-requests in progress on replicas. That makes the requests potentially access inconsistent partially deleted data.
The fix consists of multiple steps which are being sent as separate patchsets. Otherwise there would be no progress for too long while I am busy with non-vshard activities in the meantime.
#173
> Bucket ref protection on replicas - part 1 - new fail-safe measures

- test/router/reconnect_to_master.result
- test/router/reconnect_to_master.test.lua
Counting known buckets on router at first time in this test was not
stable as sometimes discovery_fiber didn't have time to start discovery
process.
Let's start router with disabled discovery, make sure the router doesn't
know any buckets, enable discovery mode and wait until it gets all
buckets from replica.
Closes #304
> test: fix flaky router/reconnect_to_master

- test/instances/router.lua
- test/luatest_helpers/vtest.lua
- test/router-luatest/router_test.lua
- vshard/error.lua
- vshard/router/init.lua
This patch introduces protecting router's API while its configuration
is not done as accessing these functions at that time is not safe and
can cause low level errors like 'bad arguments' or 'no such function'.
Now all non-trivial vshard.router functions are disabled until
vshard.router.cfg (or vshard.router.new) is finished and error is
raised in case of an attempt to access them.
Manual API's enabling/disabling is also introduced in this patch.
The behavior of router's protection is similar to the storage's one.
Closes #291
> router: auto and manual enable/disable

- test/router/router2.result
- test/router/router2.test.lua
See the commit message. The test was runned 250 times locally: the problem seems to be gone.
Closes #358
> test: fix flaky router/router2.test.lua

- test/luatest_helpers/vtest.lua
- test/router-luatest/router_test.lua
- test/storage/recovery.result
- test/storage/recovery.test.lua
- vshard/replicaset.lua
Currently if we kill net.box's fibers the connection goes into
`error_reconnect` state. However, it's not reconnecting anymore.
This patch introduces reconnecting in that case. It should be used
wisely, though. Fiber's killing doesn't happen instantly and if the
user doesn't wait util fiber's status is `dead` and makes the request
immediately, exception will be probably thrown as the fiber can die
in the middle of request.
So, after fiber kill wait until it's really dead and make a request
only after that.
Closes #341
> replicaset: reconnect after fiber kill

- test/router/suite.ini
Tarantool's CI fails constantly on router/router.test.lua.
Let's disable this test before the fix is commited.
> ci: disable router/router.test.lua

- test/multiple_routers/multiple_routers.result
- vshard/error.lua
This patch solves the problem when the error argument and the error name variable match, the variable is overwritten.
https://github.com/tarantool/vshard/blob/c508c8228ec81872cd246d3e062294a12d2d3e5d/vshard/error.lua#L109-L113
On line 256 we add the `name` key to ret, and on line 261 we overwrite it
https://github.com/tarantool/vshard/blob/c508c8228ec81872cd246d3e062294a12d2d3e5d/vshard/error.lua#L255-L261
> Fixed rewrited error arguments

- test/storage/storage.result
- test/storage/storage.test.lua
Sometimes it was failing (both with and without output) with an error in .reject file that `vshard` variable wasn't defined after storage_1_a restart.
The reason was that the restart was done with `wait=False` param. But there is no reason for it. Maybe there was before, but now the waiting is certainly fine.
Without the waiting it could happen that box.cfg is called and listen is done, but box.cfg didn't end yet and
`vshard = require('vshard')` apparently isn't done.
Closes #378
NO_DOC=bugfix
> test: fix flaky storage/storage.test.lua

- test/storage-luatest/storage_2_test.lua
Sometimes the ref wasn't deleted as the replica_a wasn't
properly synchronized with the master due to misprint in
wait_vclock_of.
Closes #375
NO_DOC=bugfix
> test: fix flaky storage/storage_2_test.lua

- vshard/storage/init.lua
- vshard/util.lua
tarantool/tarantool#7904 exports schema version to public API and Lua: start using it, when available, instead of unreliable internal API.
Closes #381
> storage: fix usage of Tarantool internal API for getting schema version

- .github/workflows/fast_testing.yml
The list of installed apt packages for default github images constantly changes. These cause the fail of building tarantool from the master branch on CI.
Let's install all packages, described in tarantool's build docs. Already installed ones will be just skipped by the apt program.
NO_TEST=ci
NO_DOC=ci
> ci: install all dependencies from doc for build

- .github/workflows/fast_testing.yml
Currently when running CI on 2.7 and 2.8 versions of tarantool
the 2.6.0-0-g47aa4e01e is being installed instead.
Fetching versions with setup-tarantool doesn't work properly with
ubuntu-22.04, so, let's use 20.04, as it's done in all other repos.
Let's also update setup-tarantool version while we're here.
Co-authored-by: Yaroslav Lobankov <y.lobankov@tarantool.org>
NO_TEST=ci
NO_DOC=ci
> ci: fix ubuntu version

- test/unit-luatest/util_test.lua
- vshard/replicaset.lua
- vshard/router/init.lua
- vshard/util.lua
Currently map_reduce (or any other test related to the functions, in
which loop over futures is used) can fail with the usage exception
due to the fact, that negative values are not allowed in wait_result.
This commit introduces new util function, which is supposed to be used
instead of wait_result. It throws box.error.TIMEOUT in case of a
negative value as argument.
Note, that errors are inconsistent: the function may return either
TimedOut error (which is one, returned from the original wait_result)
or box.error.TIMEOUT.
Closes https://github.com/tarantool/vshard/issues/384
NO_DOC=bugfix
> test: fix flaky router/map_reduce

- test/storage-luatest/bucket_triggers_test.lua
Currently several tests are disabled on mvcc. This was done due to the bugs: tarantool/tarantool#7945 and tarantool/tarantool#7977. They are claimed to be fixed now, the tests are stable.
So, let's enable them back.
Closes #394
NO_DOC=ci
> ci: enable former flaky tests on mvcc

- .github/workflows/fast_testing.yml
- vshard/consts.lua
- vshard/init.lua
Add versioning support, now the module api has `_VERSION` hardcoded variable. Is part of the task [1].
1. https://github.com/tarantool/roadmap-internal/issues/204
> api: add hardcoded versioning support

- test/rebalancer/rebalancer.result
- test/rebalancer/rebalancer.test.lua
Currently the test hangs sometimes on the line, which waits for the message "Rebalance routes are sent" to appear in logs.
According to the logs this message appears, when hang happens, but it is located before the bunch of "aa..a", which means, that rebalancer managed to send routes before waiting actually started.
This happens due to the fact, that rebalancer is waked up before waiting. Let's not do that.
Closes #360
NO_DOC=testfix
> test: fix flaky rebalancer/rebalancer.test.lua

- test/luatest_helpers/server.lua
- test/storage-luatest/storage_1_1_test.lua
- test/storage/storage_1_1.lua
- test/unit-luatest/util_test.lua
- test/upgrade/upgrade.result
- test/upgrade/upgrade.test.lua
- vshard/storage/init.lua
- vshard/util.lua
It is not released yet and not even pushed to master branch. But vshard has to be ready in advance to make the integration tests pass. For trying 3.0 yourself use https://github.com/tarantool/tarantool/pull/8289.
> Support Tarantool 3.0

- test/upgrade/upgrade.result
- test/upgrade/upgrade.test.lua
Currently, the upgrade test fails on Tarantool 3.0 during git checkout.
The error message says: "fatal: reference is not a tree," which means
that the commit hash is not valid.
Let's replace corrupted hash with the correct one.
> Fix git checkout in upgrade test

- test/luatest_helpers/vtest.lua
- test/router-luatest/reload_test.lua
- vshard/router/init.lua
Currently reloading from versions before commit https://github.com/tarantool/vshard/commit/dd70cfb2c5ec36ab7d5355b0024e5f6d21bb8f9f
("router: auto and manual enable/disable") doesn't work, as
variables `is_enabled` and `api_call_cache` weren't handled
properly. Let's set `is_enabled` flag to true on reload for
backward compatibility. As for `api_call_cache` it should be
set on router configuration, not its creation, as reconfiguration
is invoked anyway on reload.
The commit also introduces a test, which checks availability of
basic services and methods, when the router module is reloaded to
the new version.
Closes https://github.com/tarantool/vshard/issues/141
NO_DOC=bugfix
> test: introduce router reload test

- test/router/router.result
- test/router/router.test.lua
Currently the test may fail on retrieving info about buckets after
stopping the master. The router.call is made before we check statuses
of these buckets.
Deleting this call always results in `unreachable` state for buckets,
which means that if this call is done quickly we get test flakiness, as
failover sometimes doesn't have time to update nearest available replica
object.
Let's explicitly wake up failover and wait, until replica object is
updated.
Closes https://github.com/tarantool/vshard/issues/389
NO_DOC=testfix
> test: fix flaky router/router.test.lua

- test/instances/storage.lua
- test/luatest_helpers/vtest.lua
- test/rebalancer/bucket_ref.result
- test/rebalancer/bucket_ref.test.lua
- test/rebalancer/receiving_bucket.result
- test/rebalancer/receiving_bucket.test.lua
- test/storage-luatest/storage_1_1_1_test.lua
- test/storage/recovery_errinj.result
- test/storage/recovery_errinj.test.lua
- test/storage/ref.result
- test/storage/ref.test.lua
- vshard/storage/init.lua
Currently buckets with 'active' status can appear on several shards in case of manual use of vshard.storage.bucket_send() in the following situation: storage S1 has bucket B, which is sent to S2, but then connection broke. The bucket is in the state S1 {B: sending-to-s2}, S2 {B: active}. Now if the user will do vshard.storage.bucket_send(S2 -> S3), then we will get this: S1 {B: sending-to-s2}, S2: {}, S3: {B: active}. Now when recovery fiber will wakeup on S1, it will see that B is sending-to-s2 but S2 doesn't have the bucket. Recovery will then assume that S2 already deleted B, and will recover it on S1. Now we have S1 {B: active} and S3 {B: active}, doubled buckets situation.
Let's fix that by turning local bucket to SENT and only after that the remote bucket to ACTIVE. It's safe to do, …
> storage: partly fix doubled buckets

- README.md
- example/router.lua
- example/storage.lua
- test/failover/box_1_a.lua
- test/failover/config.lua
- test/failover/router_1.lua
- test/lua_libs/storage_template.lua
- test/misc/reconfigure.result
- test/misc/reconfigure.test.lua
- test/misc/storage_3_a.lua
- test/multiple_routers/router_1.lua
- test/multiple_routers/storage_1_1_a.lua
- test/rebalancer/box_1_a.lua
- test/rebalancer/router_1.lua
- test/router/box_1_a.lua
- test/router/router_2.lua
- test/router/router_3.lua
The main reason of this change is that we're going to introduce a new built-in module `config`. See https://github.com/tarantool/tarantool/issues/8724 for details.
Introducing a new module in the global namespace is legal according to our compatibility rules. Quoted from https://github.com/orgs/tarantool/discussions/6182:
> Adding a new built-in module or a new global value is considered as
> the compatible change.
Moreover, in the real-world applications configs may be changed and reloaded, so they likely will be loaded using dofile() or loadfile() without require()'s caching.
> test: use dofile() for configs instead of require

- test/storage-luatest/storage_1_test.lua
- vshard/storage/init.lua
Currently, if function was created as C stored procedure or as Lua
persistent function (with body argument) via box.schema.func.create,
all types of router.call and router.map_callrw cannot find it and
return `Procedure 'name' is not defined` error.
This is cased by the fact that both of these function use local_call,
which invokes net_box.self.call. It didn't work with these type of
functions before Tarantool 3.0.0-beta1-18. Let's use box.func, where
it's needed instead of net_box.self.call in local_call.
Closes https://github.com/tarantool/vshard/issues/436
NO_DOC=bugfix
> storage: fix local_call not finding C stored procedures

- test/luatest_helpers/vtest.lua
- test/storage-luatest/schema_management_mode_test.lua
- test/storage-luatest/storage_1_test.lua
- test/unit-luatest/config_test.lua
- test/unit-luatest/storage_exports_test.lua
- test/unit/upgrade.result
- test/unit/upgrade.test.lua
- test/upgrade/upgrade.result
- test/upgrade/upgrade.test.lua
- vshard/cfg.lua
- vshard/storage/CMakeLists.txt
- vshard/storage/export_log.lua
- vshard/storage/exports.lua
- vshard/storage/init.lua
- vshard/storage/schema.lua
- vshard/util.lua
The patch introduces a new option `schema_management_mode` which allows to turn off automatic access management (users, grants, function exports). It also adds helper functions for exports deploy.
Closes #435.
> Config option to disable user management

- example/router.lua
- test/failover/cluster_changes.result
- test/failover/cluster_changes.test.lua
- test/failover/failover.result
- test/failover/failover.test.lua
- test/failover/failover_errinj.result
- test/failover/failover_errinj.test.lua
- test/failover/router_1.lua
- test/lua_libs/util.lua
- test/luatest_helpers/server.lua
- test/misc/bad_uuid_router.lua
- test/misc/reconfigure.result
- test/misc/reconfigure.test.lua
- test/multiple_routers/multiple_routers.result
- test/multiple_routers/multiple_routers.test.lua
- test/multiple_routers/router_1.lua
- test/rebalancer/restart_during_rebalancing.result
- test/rebalancer/restart_during_rebalancing.test.lua
- test/rebalancer/router_1.lua
- test/rebalancer/stress_add_remove_rs.result
- test/rebalancer/stress_add_remove_rs.test.lua
- test/rebalancer/stress_add_remove_several_rs.result
- test/rebalancer/stress_add_remove_several_rs.test.lua
- test/router-luatest/router_test.lua
- test/router/router_2.lua
- test/router/router_3.lua
- test/router/wrong_config.result
- test/router/wrong_config.test.lua
- test/storage-luatest/box_cfg_mode_test.lua
- vshard/router/init.lua
1. https://github.com/tarantool/doc/issues/3895 should be closed after merging. 
2. https://github.com/tarantool/vshard/issues/353 should be reopened and closed as not planned.
Note, that https://github.com/tarantool/vshard/commit/a5304557e052f95541ab44953c5aa882f9f58dce intentionally wasn't reverted. I suppose, it's correct. We should not set `box.cfg.replication_timeout` during config generation. It should be done inside template, storages need this option, routers - don't.
> router: revert dropping box.cfg and introduce `box_cfg_mode`

- test/unit-luatest/storage_exports_test.lua
- vshard/storage/exports.lua
The deploy_privs() function will now grant the required privileges to a user or a role.
Follow-up #435
> storage: add support for roles in deploy_privs()

- test/replicaset-luatest/replicaset_3_test.lua
- vshard/replicaset.lua
During upgrade to Tarantool 3.0.0 there's a time, when instance name have not been set yet. If vshard strictly validates names on connection, it leads to the cluster unavailability by the time, when all names are configured.
This commit softens the check and allows name to be nil, when instance UUID is specified in configuration, only UUID is validated in such case.
In conclusion we have the following checks on connection:
1. UUID is validated in the following cases:
a. When `identification_mode` is `uuid_as_key`
b. When `identification_mode` is `name_as_key` and replica.uuid
is specified
2. Instance name is validated only when `identification_mode` is
`name_as_key` and can work in the following modes:
a. Strict validation (nil instance name is not allowed), when
replica.uuid is not …
> replicaset: soften name validation

- test/storage-luatest/storage_1_test.lua
- vshard/storage/init.lua
Currently hot reload failes, when named identification is used. It is cause by the fact, that we still pass uuid in storage.cfg during reload.
Let's pass id instead of UUID. It's either uuid or name, depeding on identification_mode. If reload is done from the old version, where no replica.id exists, we fall back to replica.uuid.
Closes #464
NO_DOC=bugfix
> storage: fix hot reload with named identification

- test/unit-luatest/storage_exports_test.lua
- test/unit-luatest/version_test.lua
- vshard/storage/exports.lua
- vshard/version.lua
storage: fix schema log message
exports_deply_funcs() used to log the core version as nil. The problem
is the fact, that table.concat was used for core version string, so the
complied exports always had nil instead of core_version.
table.concat doesn't work with non-array tables, as they have no defined
order. Let's explicitly define __tostring function for version and use
it in order to log core version.
Closes https://github.com/tarantool/vshard/issues/465
NO_DOC=bugfix
> storage: fix schema log message

- test/replicaset-luatest/replicaset_3_test.lua
- vshard/replicaset.lua
- vshard/util.lua
Changes a needed to support ipv6 in cartridge
This changes needed for https://github.com/tarantool/cartridge/pull/2166
> Fix for working with ipv6 addrs in cartridge

- example/router.lua
- test/failover/router_1.lua
- test/misc/bad_uuid_router.lua
- test/rebalancer/router_1.lua
- test/router/router_2.lua
- test/router/router_3.lua
In the near future we plan to test Tarantool installed from a DEB/RPM package. Since 3.0.0-alpha1 release Tarantool packages don't have the tarantoolctl utility inside.
tarantoolctl was ebmed to the test-run project inself. The submodule has been updated to the latest version.
> ci: bump test-run

- test/failover/failover.result
- test/failover/failover.test.lua
Router pings replicas and if they cannot respond in
failover_ping_timeout, it detaches connection from this replica.
The test checks, that connection is not closed, when long response is
done, even if failover_ping_timeout is small.
However, when the connection is detached, it can be garbage collected,
which leads to 'Connection closed' error. Let's stop Lua GC for the
connection by creating reference to it.
Related to https://github.com/tarantool/tarantool/issues/9629
NO_DOC=test
> test: fix flaky failover/failover.test.lua

- test/replicaset-luatest/vconnect_test.lua
- test/router/router.result
- vshard/replicaset.lua
Currently, the name validation is not used, when locate_master() is called. It makes an explicit call via the connection to obtain a future object in order to figure out, whether the node is a master.
We should not make any calls to a replica until the time, we definitely know, that its name and uuid was validated. Let's use replica_call instead of conn.call.
Follow-up #426
NO_DOC=bugfix
> replicaset: validate name in replicaset_locate_master

- test/replicaset-luatest/vconnect_test.lua
This patch brings an update to the test to reflect the correct behavior after tarantool/tarantool#9489 is fixed. The test against correct behavior is temporarily disabled until tarantol/tarantool#9803 is merged.
This patch needs to be merged before https://github.com/tarantool/tarantool/pull/9803.
Part of #456
> test: update `async_no_yield` test from `vconnect` test group

- test/replicaset-luatest/vconnect_test.lua
This patch re-enables the test to reflect the correct behavior after the fix for tarantool/tarantool#9489 bug was merged.
Closes #456
> test: re-enable `async_no_yield` test from `vconnect` test group

- test/router/router2.result
- test/router/router2.test.lua
In test `router/router2` we get vclock from one instance and wait for this vclock on another one. The problem is we get vclock with local lsn which is independent on each instance - the commit fixes this mistake.
> test: ignore zero lsn when waiting for vclock in router2 test

- .github/workflows/fast_testing.yml
- .github/workflows/lint.yml
- .github/workflows/publishing.yml
- .github/workflows/reusable_testing.yml
This commit bumps the Ubuntu distro version up to 24.04 (noble) in all existing workflows, since the Ubuntu 20.04 (focal) image support will be dropped today in the GitHub actions.
See also: actions/runner-images#11101
Closes tarantool/vshard#520
NO_DOC=ci
NO_TEST=ci
> ci: bump Ubuntu version in workflows

- CMakeLists.txt
- test/CMakeLists.txt
New cmake 4.0.0 removed compatibility with all version prior to 3.5
NO_DOC=build
NO_TEST=build
> build: bump cmake_minimum_required to 3.5

- .github/workflows/cartridge_integration.yml
- .github/workflows/integration.yml
- test/router-luatest/router_3_3_test.lua
- vshard/replicaset.lua
The commit d017a9ed18767 ("replicaset: speed up the read-only calls") has broken the fallback to master in read-only calls if master was in backoff. Previoulsy, we checked the backoff and dropped it right during calls, but after that commit only failover service started to do that, which caused request failure even if backoff interval already passed, because only on failover wakeup the instance could be restored.
This should not work like that and in case of fallback to master in read-only calls we should explicitly check and drop backoff, if it's possible, so that request can pass.
I also had an idea to restore the `health_status` of the replica, if `replication_status` is `GREEN` and drop backoff right after every successful call, but we should not do that, since a lot of services use …
> replicaset: fix read-only request not fallback to master
